<?php

namespace Factu\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BdlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BdlRepository extends EntityRepository
{
	public function getNextNumBdl() {
	    $query = $this->getEntityManager()
	        ->createQuery('SELECT b FROM FactuAppBundle:Bdl b ORDER BY b.numBdl desc')
	        ->setMaxResults(1);
	        
	    try {
	    	$bdl = $query->getSingleResult();
	    	if ($bdl != null) {
	    		return $bdl->getNumBdl() + 1;
	    	} else {
	        	return 1;
	        } 
	    } catch (\Doctrine\ORM\NoResultException $e) {
	        return 1;
	    }
	}

	public function getBdlsByYearMonthDay($month, $year) {
		$emConfig = $this->getEntityManager()->getConfiguration();
	    $emConfig->addCustomDatetimeFunction('YEAR', 'DoctrineExtensions\Query\Mysql\Year');
	    $emConfig->addCustomDatetimeFunction('MONTH', 'DoctrineExtensions\Query\Mysql\Month');

	    $qb = $this->createQueryBuilder('c');
	    $qb->select('c')
	       ->where('YEAR(c.dateBdl) = :year')
	       ->andWhere('MONTH(c.dateBdl) = :month');

	    $qb->setParameter('year', $year)
	       ->setParameter('month', $month);

	    $qb->orderBy('c.dateBdl', 'ASC');

	   	$listResult = $qb->getQuery()->getResult();
	    return $listResult;
	}

}
