<?php

namespace Factu\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
	public function getNextNumClient() {
	    $query = $this->getEntityManager()
	        ->createQuery('SELECT c FROM FactuAppBundle:Client c ORDER BY c.numClient desc')
	        ->setMaxResults(1);
	        
	    try {
	    	$client = $query->getSingleResult();
	    	if ($client != null) {
	    		return $client->getNumClient() + 1;
	    	} else {
	        	return 0;
	        } 
	    } catch (\Doctrine\ORM\NoResultException $e) {
	        return null;
	    }
	}
}
