<?php

namespace Factu\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommandeServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeServiceRepository extends EntityRepository
{
}
