<?php

namespace Factu\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCategoryRepository extends EntityRepository
{
	public function getFollowedStatCategories() {
	    $query = $this->getEntityManager()
	        ->createQuery('SELECT c FROM FactuAppBundle:ProductCategory c WHERE c.isFollowedStat = 1');
	        
	    try {
	    	return $query->getResult(); 
	    } catch (\Doctrine\ORM\NoResultException $e) {
	        return null;
	    }
	}
}
