<?php

namespace Factu\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
	public function getFollowedStatProduct() {
	    $query = $this->getEntityManager()
	        ->createQuery('SELECT p FROM FactuAppBundle:Product p WHERE p.isFollowedStat = 1');
	        
	    try {
	    	return $query->getResult(); 
	    } catch (\Doctrine\ORM\NoResultException $e) {
	        return null;
	    }
	}
}
